# Generated by Django 5.0.6 on 2024-07-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_data',
            new_name='date_purchased',
        ),
    ]
